
#ansible-playbook playbook_configuration_ec2.yml -i hosts 

---
- name: Let's copy our executable script to remote location, execute script and get result back.
  hosts: worker
  remote_user: ubuntu
  tasks:
     - name: Transfer executable script
       copy: src=./configuration_script_worker.sh dest=/home/ubuntu/ mode=0777
 
     - name: Execute the script
       command: sh /home/ubuntu/configuration_script_worker.sh 
  
